[package]
name = "disas"
description = "Disassembler"
version = "0.1.0"
license = "GPL-3.0-only"
keywords = ["disassembler"]
authors = ["Denis Drakhnia <numas13@gmail.com>"]
repository = "https://github.com/numas13/disas"
edition = "2021"
rust-version = "1.70"

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
object = "0.34"
disasm = { version = "0.1.0", features = ["all-arch", "print"] }
