[package]
name = "disas"
description = "Disassembler"
version = "0.1.0"
license = "GPL-3.0-only"
keywords = ["disassembler"]
authors = ["Denis Drakhnia <numas13@gmail.com>"]
repository = "https://github.com/numas13/disas"
edition = "2021"
rust-version = "1.70"

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["all-arch", "block-buffering"]
block-buffering = []

riscv = ["disasm/riscv"]
all-arch = [
    "riscv",
]

[dependencies]
object = "0.34"
disasm = { version = "0.3.2", features = ["print"] }
bpaf = { version = "0.9", features = ["autocomplete", "dull-color"] }
